### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by majecty**

### CODE REVIEW

**Comment by HoOngEe** [comment]
`yarn lint` failed

**Comment by HoOngEe** [comment]
I don't know about the reason, but build fails

**Comment by majecty** [comment]
The error says that there is no module '@babel/helper-call-delegate'. However, there is no explicit usage of the module.
I'll dig into it.

The error message:
```
Error: [BABEL] /mnt/sonnyexternal/juhyung/code/kodebox/codechain-web-wallet/src/index.tsx: Cannot find module '@babel/helper-call-delegate'
Require stack:
```

**Comment by majecty** [comment]
It's too old. I'll do it later from scratch.

**Pull request closed without merging**
